AccuMVC/Models/CurrentWeatherModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AccuMVC.Models
{
	public class CurrentWeatherModel
	{
		public string WeatherImage { get; set; }
		public string WeatherText { get; set; }
		public string MetricTemp { get; set; }
		public string ImperialTemp { get; set; }
	}
}

AccuMVC/Models/ForecastWeatherModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AccuMVC.Models
{
	public class ForecastWeatherModel
	{
		public string FormattedTime { get; set; }
		public string ForecastIcon { get; set; }
		public string IconPhrase { get; set; }
		public string Temperature { get; set; }
		public string TemperatureUnit { get; set; }
	}
}

AccuMVC/Models/LocationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AccuMVC.Models
{

	//I'd be tempted to add MVC attributes to these model, but I don't use them (for example, 
	// I don't need to label any fields with a DisplayName on these pages).  And it looks
	// like most of the attributes I'd consider are used for data validation and DB 
	// binding, which aren't issues here.
	public class LocationModel
	{
		public int Key { get; set; }
		public string LocalizedName { get; set; }
		public string PrimaryPostalCode { get; set; }
		public string Country { get; set; }
		public string AdministrativeAreaLocalizedName { get; set; }
	}
}

AccuMVC/Models/LocationSearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AccuMVC.Models
{
	public class LocationSearchModel
	{
		public string SearchText { get; set; }
		public List<LocationModel> SearchResults { get; set; }
		public bool Error { get; set; }
		public LocationSearchModel()
		{
			//would of course be empty in production, just making testing easier at the moment
			SearchText = "State College";
			SearchResults = new List<LocationModel>();
			Error = false;
		}
	}
}

AccuMVC/Models/LocationWeatherModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AccuMVC.Models
{
	public class LocationWeatherModel
	{
		public string Key { get; set; }
		public CurrentWeatherModel CurrentWeather { get; set; }
		public List<ForecastWeatherModel> ForecastWeather { get; set; }
		public bool Error { get; set; }
	}
}

AccuMVC/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using AccuMVC.Models;
using AccuMVC.Utility;
using Newtonsoft.Json.Linq;

namespace AccuMVC.Controllers
{
    public class LocationController : Controller
    {
        // GET: Location
		public ActionResult Index(string SearchText)
        {
			LocationSearchModel LocSearch = new LocationSearchModel();
			LocSearch.SearchText = SearchText == null ? LocSearch.SearchText : SearchText;
			GetSearchResults(LocSearch);
            return View(LocSearch);
        }
		//This seems oddly placed because the result is determined by changing the LocationSearchModel.SearchText
		// But I didn't want to include logic directly in the Model to handle it.  In MVVM I'd use a VM property that
		// is bound to the model, but updates the search results within the setter.
		private void GetSearchResults(LocationSearchModel Model)
		{
			//reset the error flag
			Model.Error = false;
			if(Model.SearchText != "")
			{
				//clear any previous search
				Model.SearchResults.Clear();

				//hit API
				string retVal = RESTRequest.GetREST("http://" + WebConfigurationManager.AppSettings["AccuWeatherSite"], 
					"/locations/v1/search?q=" + Model.SearchText + "&apikey=" + WebConfigurationManager.AppSettings["AccuWeatherAPIKey"]);

				//check for any strangeness
				if (!string.IsNullOrEmpty(retVal))
				{
					try
					{
						//get an object we can use
						JArray jObject = JArray.Parse(retVal);
						for (int i = 0; i < jObject.Count; i++)
						{
							//create our local object and add it to the model
							LocationModel res = new LocationModel();
							res.Key = int.Parse(jObject[i]["Key"].ToString());
							res.LocalizedName = jObject[i]["LocalizedName"].ToString();
							res.PrimaryPostalCode = jObject[i]["PrimaryPostalCode"].ToString();
							res.Country = jObject[i]["Country"]["LocalizedName"].ToString();
							res.AdministrativeAreaLocalizedName = jObject[i]["AdministrativeArea"]["LocalizedName"].ToString();
							Model.SearchResults.Add(res);
						}
					}
					catch (Exception ex)
					{
						//log error here
						//set the model error flag so we can tell the user something went wrong on the backend
						Model.Error = true;
					}
				} else
				{
					//something went wrong with the API call
					Model.Error = true;
				}
			}
		}
    }
}

AccuMVC/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using AccuMVC.Models;
using AccuMVC.Utility;
using Newtonsoft.Json.Linq;

namespace AccuMVC.Controllers
{
    public class WeatherController : Controller
    {
        // GET: Weather
        public ActionResult Index(string id)
        {
			LocationWeatherModel Model = new LocationWeatherModel { Key = id };
			Model.Error = false;
			GetCurrent(Model);
			if(Model.Error == false)
				GetForecast(Model);
            return View(Model);
        }
		/// <summary>
		/// Given a model with a valid location key, attempts to retrieve the current weather
		/// </summary>
		/// <param name="Model"></param>
		private void GetCurrent(LocationWeatherModel Model)
		{
			Model.CurrentWeather = new CurrentWeatherModel();
			string retVal = RESTRequest.GetREST("http://" + WebConfigurationManager.AppSettings["AccuWeatherSite"]
				, "/currentconditions/v1/" + Model.Key + ".json?apikey="+ WebConfigurationManager.AppSettings["AccuWeatherAPIKey"] + "&language=en");
			if (!string.IsNullOrEmpty(retVal))
			{
				try
				{
					JArray jObject = JArray.Parse(retVal);
					for (int i = 0; i < jObject.Count; i++)
					{
						Model.CurrentWeather.ImperialTemp = jObject[i]["Temperature"]["Imperial"]["Value"].ToString();
						Model.CurrentWeather.MetricTemp = jObject[i]["Temperature"]["Metric"]["Value"].ToString();
						Model.CurrentWeather.WeatherImage = GetIcon(int.Parse(jObject[i]["WeatherIcon"].ToString()));
						Model.CurrentWeather.WeatherText = jObject[i]["WeatherText"].ToString();
						//although this comes as an array, it isn't clear why in the docs.  Just take the first value for now
						// but leave as a loop for later in case there are other values we can use
						break;
					}
				}
				catch (Exception ex)
				{
					//log error here
					Model.Error = true;
				}
			} else
			{
				Model.Error = true;
			}
		}
		/// <summary>
		/// Given a model with a valid location key, attempts to retrieve the current forecast
		/// </summary>
		/// <param name="Model"></param>
		private void GetForecast(LocationWeatherModel Model)
		{
			Model.ForecastWeather = new List<ForecastWeatherModel>();
			string retVal = RESTRequest.GetREST("http://" + WebConfigurationManager.AppSettings["AccuWeatherSite"], 
				"/forecasts/v1/hourly/12hour/" + Model.Key + ".json?apikey=" + WebConfigurationManager.AppSettings["AccuWeatherAPIKey"] + "&language=en");
			if (!string.IsNullOrEmpty(retVal))
			{
				try
				{
					JArray jObject = JArray.Parse(retVal);
					for (int i = 0; i < jObject.Count; i++)
					{
						ForecastWeatherModel forecast = new ForecastWeatherModel();
						forecast.ForecastIcon = GetIcon(int.Parse(jObject[i]["WeatherIcon"].ToString()));
						DateTime dt = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
						dt = dt.AddSeconds(double.Parse(jObject[i]["EpochDateTime"].ToString()));
						forecast.FormattedTime = dt.ToLocalTime().ToShortTimeString();
						forecast.IconPhrase = jObject[i]["IconPhrase"].ToString();
						forecast.Temperature = jObject[i]["Temperature"]["Value"].ToString();
						forecast.TemperatureUnit = jObject[i]["Temperature"]["Unit"].ToString();
						Model.ForecastWeather.Add(forecast);
					}
				}
				catch (Exception ex)
				{
					//log error here
					Model.Error = true;
				}
			} else
			{
				Model.Error = true;
			}
		}
		/// <summary>
		/// Creates a 0-padded string to be used with AccuWeather icons
		/// </summary>
		/// <param name="id">id of the icon as an integer</param>
		/// <returns>URL to an AccuWeather icon</returns>
		private string GetIcon(int id)
		{
			string icoNum = "";
			if(id < 10)
			{
				icoNum = "0" + id.ToString();
			} else
			{
				icoNum = id.ToString();
			}
			return "http://apidev.accuweather.com/developers/Media/Default/WeatherIcons/" + icoNum + "-s.png";
		}
    }
}

AccuMVC/Views/Location/Index.cshtml
@model AccuMVC.Models.LocationSearchModel

@using(Html.BeginForm())
{
    <div>
        @Html.TextBoxFor(model => model.SearchText)
        <input type="submit" value="Search" />
    </div>
}
    <div>
        @if(Model.Error)
        {
            <div>An error occured while searching for your location.  Please try again later.</div>
        }
        @foreach (var item in Model.SearchResults)
        {
            @Html.Partial("_SearchResult", item);
        }
    </div>

AccuMVC/Views/Location/_SearchResult.cshtml
@model AccuMVC.Models.LocationModel

<div class="searchResult">
    <div>@Html.DisplayFor(model => model.LocalizedName)</div>
    <div>@Html.DisplayFor(model => model.AdministrativeAreaLocalizedName)</div>
    <div>@Html.DisplayFor(model => model.PrimaryPostalCode)</div>
    <div>@Html.DisplayFor(model => model.Country)</div>
    <div>@Html.ActionLink("Select","Index", "Weather", new { id = Model.Key }, null)</div>
</div>

AccuMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AccuWeather API Test</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Weather Search", "Index", "Location", new { }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - J Lothian</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

AccuMVC/Views/Weather/Index.cshtml
@model AccuMVC.Models.LocationWeatherModel

@Html.Partial("_CurrentWeatherView", Model.CurrentWeather)

<div>
    <h2>12 Hour Forecast</h2>
    <div>
        @if (Model.Error)
        {
            <div>An error occured while retrieving local weather information.  Please try again later.</div>
        }
        @foreach (var item in Model.ForecastWeather)
        {
            @Html.Partial("_ForecastWeatherView", item)
        }
    </div>
</div>

AccuMVC/Views/Weather/_CurrentWeatherView.cshtml
@model AccuMVC.Models.CurrentWeatherModel

<div>
    <h2>Current</h2>
    <img src="@Url.Content(ViewData.Model.WeatherImage)" class="wimg" /><div>@Html.DisplayFor(Model => Model.WeatherText)</div>
    <div class=""><span>@Html.DisplayFor(Model => Model.ImperialTemp)</span><span>&deg;F</span></div>
    <div><span>@Html.DisplayFor(Model => Model.MetricTemp)</span><span>&deg;C</span></div>
</div>

AccuMVC/Views/Weather/_ForecastWeatherView.cshtml
@model AccuMVC.Models.ForecastWeatherModel

<div class="foreRow">
    <div class="foreDate">@Html.DisplayFor(Model => Model.FormattedTime)</div>
    <img src="@Url.Content(ViewData.Model.ForecastIcon)" class="wimg" />
    <div class="details">
        <div class="shortTxt">@Html.DisplayFor(Model => Model.IconPhrase)</div>
        <div class="shortTxt"><span>@Html.DisplayFor(Model => Model.Temperature)</span><span>&deg;</span><span>@Html.DisplayFor(Model => Model.TemperatureUnit)</span></div>
    </div>
</div>